name: E2E LST Flood

on:
  # Manual runs.
  workflow_dispatch:
    inputs:
      target_environment:
        description: "Target Environment"
        required: true
        default: "performance"
      preset:
        description: "Preset: <'base' | 'basePlus' | 'basePlusSpikes'>"
        required: true
        default: "base"

defaults:
  run:
    working-directory: e2e

jobs:
  deploy_lst:
    name: Deploy LST
    runs-on: ubuntu-latest
    env:
      # Setup any secret overrides that are necessary here.
      # Most other environment variables will come from /e2e/config.json,
      # as determined by the E2E_ENVIRONMENT variable set above.
      E2E_FLOOD_API_TOKEN: ${{ secrets.E2E_FLOOD_API_TOKEN }}
      E2E_SIMULATION_SPEED: ${{ secrets.E2E_SIMULATION_SPEED }}
      E2E_FLOOD_DATA_BASEURL: ${{ secrets.E2E_FLOOD_DATA_BASEURL }}
      E2E_FINEOS_USERS: ${{ secrets.E2E_FINEOS_USERS }}
      E2E_EMPLOYER_PORTAL_USERNAME: ${{ secrets.E2E_EMPLOYER_PORTAL_USERNAME }}
      E2E_FINEOS_PASSWORD: ${{ secrets.E2E_FINEOS_PASSWORD }}
      E2E_PORTAL_PASSWORD: ${{ secrets.E2E_PORTAL_PASSWORD }}
      E2E_TESTMAIL_APIKEY: ${{ secrets.E2E_TESTMAIL_APIKEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with: { node-version: 12.x }
      - name: "Install Dependencies"
        run: npm ci
      - name: Set variables for manual run
        if: github.event_name == 'workflow_dispatch'
        run: echo "E2E_ENVIRONMENT=${{ github.event.inputs.target_environment }}" >> $GITHUB_ENV
      - name: "Deploy"
        run: npm run cli -- flood ${{ github.event.inputs.preset }} --deploy
